### PR TITLE
Feature/#068 vagrant

### PR DESCRIPTION
**Pull request by migromarj**
To run the project with Vagrant you must have VirtualBox (https://www.virtualbox.org/wiki/Downloads) and Vagrant (https://developer.hashicorp.com/vagrant/downloads) installed, and you must perform the following steps:

1. Inside the project directory terminal do 'cd Vagrant'
2. Run the command 'vagrant up'
3. Run the command 'vagrant ssh'

Once inside the virtual machine, execute:

>> cd innosoft-innoweb-1
>> sudo python3 manage.py makemigrations --settings=innoweb.deployment_settings
>> sudo python3 manage.py migrate --settings=innoweb.deployment_settings
>> sudo python3 manage.py loaddata "fixtures/initial.json" --settings=innoweb.deployment_settings
>> sudo python3 manage.py runserver 0.0.0.0:8000 --settings=innoweb.deployment_settings

Go to the host browser and put the url 'localhost:8080'.

### CODE REVIEW

**Review by IsmaelP19 — CHANGES_REQUESTED** [review]
There are several things that don't work as expected.

The most important thing is that the download certificate action doesn't work at all. I think it has to be related with statics, because the message that Django shows is the next one: 
image

The other thing I came across with is the messages related to joining an event. For instance, when you join an event the message displayed is the next one: 
image
As you can see, it doesn't load the styles.

Maybe you can load the statics route in a different way?

Anyway, you did a great job. Keep it up! 🚀🙌

**Comment by migromarj** [comment]
> There are several things that don't work as expected.
> 
> The most important thing is that the download certificate action doesn't work at all. I think it has to be related with statics, because the message that Django shows is the next one: image
> 
> The other thing I came across with is the messages related to joining an event. For instance, when you join an event the message displayed is the next one: image As you can see, it doesn't load the styles.
> 
> Maybe you can load the statics route in a different way?
> 
> Anyway, you did a great job. Keep it up! 🚀🙌

@IsmaelP19 was investigating what caused these errors and I realized that they are caused by the configuration file used for Vagrat and the path used by the page certificates. Since these changes were made in two different branches, is it okay if we create an issue and assign the two of us to fix these bugs?

**Comment by IsmaelP19** [comment]
> > There are several things that don't work as expected.
> > The most important thing is that the download certificate action doesn't work at all. I think it has to be related with statics, because the message that Django shows is the next one: image
> > The other thing I came across with is the messages related to joining an event. For instance, when you join an event the message displayed is the next one: image As you can see, it doesn't load the styles.
> > Maybe you can load the statics route in a different way?
> > Anyway, you did a great job. Keep it up! 🚀🙌
> 
> @IsmaelP19 was investigating what caused these errors and I realized that they are caused by the configuration file used for Vagrat and the path used by the page certificates. Since these changes were made in two different branches, is it okay if we create an issue and assign the two of us to fix these bugs?

Perfect idea!

**Review by juradosalado — COMMENTED** [review]
Vagrant does not seem to work in my laptop. It seems to take too much time and it produces a time out error. Maybe other collaborator of the project can try it.

**Comment by migromarj** [comment]
@IsmaelP19 all the corresponding modifications have already been made so that the certificates can be downloaded using Vagrant.
@juradosalado, don't worry, I'll assign @ezegonmac as a new reviewer to see if he can test the task without problems.

**IMPORTANT**

@IsmaelP19 @ezegonmac as vagrant downloads the repository, currently in the main branch the extensions of the sources in the "innoweb/views.py" file are as ".ttf", this has been changed in this pull request but is not reflected in main yet. I would ask you to manually change the extension to ".TTF" before doing the runserver command in vagrant, which is how after merging this pull request it will be in main, and therefore it should work like this.

**Review by IsmaelP19 — APPROVED** [review]
Now everything is running as expected. Messages are rendered with the appropiate styles and certificates now are generated without any problems.

Good job, @migromarj !! 🙌🚀

**Review by ezegonmac — APPROVED** [review]
Vagrant runs as expected. Good job Miguel 🤝

**Pull request merged**
