### PR TITLE
feat(#86): Edit README.md file

### PR DESCRIPTION
**Pull request by migromarj**
Add GitHub Actions workflow status badge, corresponding to continuous deployment with Docker.
Add steps to use the application in different ways: local installation, Docker, Vagrant or use from the Internet.

### CODE REVIEW

**Review by ezegonmac — APPROVED** [review]
Very well detailed README. Good jod as usual @migromarj 💯

**Review by IsmaelP19 — CHANGES_REQUESTED** [review]
The README is quite detailed, good job!
The only thing I would change is the title on line 5: I think is more appropiate to see 'Innosoft Innoweb' instead of 'Innosoft eventos', since that is the name of the project itself.

**Comment by migromarj** [comment]
> The README is quite detailed, good job! The only thing I would change is the title on line 5: I think is more appropiate to see 'Innosoft Innoweb' instead of 'Innosoft eventos', since that is the name of the project itself.

True, I had called it that way because as we have called the web 'INNOSOFT eventos', but you are absolutely right that what appears in the readme is the name of the project. Thank you very much for noticing and informing me.

**Review by IsmaelP19 — APPROVED** [review]
Everything is perfect now. Good job! 🚀😎

**Pull request merged**
