### PR TITLE
feat(#35): Add file for continuous integration with GitHub Actions

### PR DESCRIPTION
**Pull request by migromarj**
Created main.yml file in '.github/workflows' so that every time a 'push' is made to 'main' or any 'feature' branch and every time a pull request to 'main' is opened, all the application tests in addition to a coverage analysis by codacy. Add 'coverage' as project requirement.

### CODE REVIEW

**Review by ezegonmac — APPROVED** [review]
All seems to be right 😁👌. --keepdb could be a problem in the future but we can fix it when we merge to main

**Review by IsmaelP19 — APPROVED** [review]
The main file seems to be ok.
Well done! 🚀🙌

**Comment by migromarj** [comment]
@IsmaelP19 @ezegonmac I have added a few lines in the file associated with GitHub Actions to verify and configure the database, also I have made a small change in the file 'development_settings.py' changing the HOST from 'localhost' to '127.0.0.1'. Do you agree with these changes?

**Comment by ezegonmac** [comment]
> @IsmaelP19 @ezegonmac I have added a few lines in the file associated with GitHub Actions to verify and configure the database, also I have made a small change in the file 'development_settings.py' changing the HOST from 'localhost' to '127.0.0.1'. Do you agree with these changes?

All right👍

**Comment by IsmaelP19** [comment]
> @IsmaelP19 @ezegonmac I have added a few lines in the file associated with GitHub Actions to verify and configure the database, also I have made a small change in the file 'development_settings.py' changing the HOST from 'localhost' to '127.0.0.1'. Do you agree with these changes?

I agree with it 🫡😎

**Pull request merged**
